config/routes.rb
Danjam::Application.routes.draw do
  
  resources :users do
    collection do
      get 'bios'
    end
  end

  resources :posts

  get "comments/index"
  get "comments/new"

  get "songs/bios"
  get "songs/announcements"
  
  get "chords/index"
  get "chords/edit"
  
  match "users/bios" => "users#bios"

  resources :songs
  resources :chords
  resources :comments
  resources :posts
  resources :gigs

  get "home/index"
  root to: "home#index"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :chords, :comment, :title, :url, :performers
  has_many :comments, dependent: :destroy

  validates :title, :presence => {:message => 'cannot be blank'}
  validates :url, :presence => {:message => 'cannot be blank'}

end

app/controllers/songs_controller.rb
class SongsController < AdminController
  # GET /songs
  # GET /songs.json
  layout 'backstage'
  
  def index
    @songs = Song.find(:all, :order => "title ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  def bios
    render 'bios'
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

   # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to controller: :chords, id: @song.id, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<div class="inputform">
  <%= form_for(@song) do |f| %>
    <% if @song.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

        <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li></br>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      Song
      <%= f.label "Title" %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :url %><br />
      <%= f.text_field :url %>
    </div>
    <div class="field">
      Lyrics and
      <%= f.label "Chords" %><br />
      <%= f.text_area :chords %>
    </div>
    <div class="field">
      <%= f.label :performers %><br />
      <%= f.text_area :performers %>
    </div>
    <div class="actions">
      <%= link_to "Cancel", :back %>
      <%= f.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/songs/edit.html.erb
<h1>Song Edit</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>Song Listings</h1>

  <div class="center">
    <p><%= link_to 'Add new song', new_song_path %></p>

    <p class="center">-->>><b>Click song title and a youtube video for the 
      song will open in a new tab</b><<<--</p>
    <p class="center">To edit a song and/or add or remove Performers, click 'Details' and then 'Edit' and add them to the 'Performers' text box.  Put each performer on a new line and save the edit.</p>
    <p>If you know some chords 
      feel free to click 'Details' and then 'Edit' and put them in the Comment
      field.</p>
    <p>Happy practicing!</p>
  </div>

<table class="center">
  <tr>
    <th>Title</th>
    <th>Chords</th>
    <th>Comments</th>
    <th>Details</th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><i><b><a href="<%= song.url %>" target='_blank'>
        <%= song.title %></a></i></b><br />
        <%= simple_format(song.performers) %></td>
    <td class="options"><%= link_to 'Chords & Lyrics', controller: :chords, id: song.id %> </td> 
    <td class="options"><%= link_to "Comments(#{commentsCountSong(song.id)})", controller: :comments, song_id: song.id, c_type: 'song' %> </td> 
    <td class="options"><%= link_to 'Details', action: :show, id: song.id %></td> 
  </tr>
<% end %>
</table>

app/views/songs/new.html.erb
<h1>New Song</h1>
<div class="toptext">
  <div class="center">
    <p>Recommended song title format:  "Bandname - Song Title"</p>
    <p>For the url, just find the song you want on YouTube (or elsewhere) 
      <br/>and then copy/paste the url from the browser nav bar.</p><br />
  </div>
</div>


<%= render 'form' %>

app/views/songs/show.html.erb
<h1>Song Details</h1>
<p id="notice"><%= notice %></p>

  <p class="center">
    <b>Title:</b>
    <i><b><%= @song.title %></b></i>
    <p class="center">
      <%= link_to 'Edit', edit_song_path(@song) %> |
      <%= link_to 'Back', action: :index %>
    <p>
  </p>

  <p class="center">
    <b>Url:</b>
    <%= auto_link(@song.url, html: { target: "_blank" }) %>
  </p>
</div>

<p>  	
  <div class="chords">
  	<b><u>Chords & Lyrics:</b></u><br/>
    <%= auto_link(simple_format(@song.chords)) %>
  </div>
</p>

<%= link_to 'Delete', @song, method: :delete, data: { confirm: 'Are you sure?' } %>